debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.thc.sprstudy: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://www.adapter-gwangalli.com:3306/scjavajjang?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ivill0080@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul
    hibernate:
      naming:
        physical-strategy: com.thc.realspr.TablePrefix
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false
    remote:
      restart:
        enabled: false
  freemarker:
    cache: false
  sql.init.mode: always
  #sql.init.mode: never
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha