name: Add issue or PR to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/handong-app/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
