name: Build Spring Boot Artifact

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.bru"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"

permissions:
  contents: write
  packages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "build-and-release"
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      current_date: ${{ steps.set-date.outputs.current_date }}
    steps:
      - name: Get current date and time
        id: set-date
        run: echo "current_date=$(TZ=Asia/Seoul date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    environment: SPRING_BOOT

    # 깃허브에서 제공하는 checkout 엑션 사용
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # JDK 17 설정한다.
      # temurin = Adoptium에서 제공하는 JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # gradle wrapper 파일에 실행 권한을 부여
      # gradle wrapper = 개발자가 특정 버전의 Gradle을 미리 설치하지 않고도 Gradle 빌드를 실행할 수 있게 해주는 편리한 도구
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드 엑션을 이용해서 프로젝트 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build
        env:
          REACT_APP_WEATHER_KEY: ${{ secrets.VITE_WEATHER_KEY }}

      # 다른 JOB 사용 가능하도록 artifact 생성
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/handong-feed-0.0.1-SNAPSHOT.jar
          name: spring-boot-jar

  release:
    runs-on: ubuntu-latest
    needs: [setup, build] # 이전 Job이 끝난 후에 실행
    steps:
      # artifact 다운로드
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-jar
          path: ./

      # 릴리즈 생성
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.setup.outputs.current_date }}
          release_name: "Release ${{ needs.setup.outputs.current_date }}"
          draft: false
          prerelease: false

      # 릴리즈 아티팩트 업로드
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: handong-feed-0.0.1-SNAPSHOT.jar
          asset_name: handong-feed-0.0.1-SNAPSHOT.jar
          asset_content_type: application/java-archive

  docker:
    runs-on: ubuntu-latest
    needs: [setup, build] # 이전 Job이 끝난 후에 실행

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # artifact 다운로드
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-jar
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 빌드 생성 - 이전 Job Steps 에서 생성한 artifact 사용.
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        # if: ${{ !env.ACT }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.REPOSITORY_OWNER }}/handong-feed-app:latest
            ghcr.io/${{ github.repository_owner }}/handong-feed-app:${{ needs.setup.outputs.current_date }}
            ghcr.io/${{ github.repository_owner }}/handong-feed-app:build-${{ github.run_number }}
          labels: |
            org.opencontainers.image.source=${{ github.SERVER_URL	}}/${{ github.REPOSITORY }}
            org.opencontainers.image.revision=${{ github.SHA }}
          build-args: |
            JAR_FILE=./handong-feed-0.0.1-SNAPSHOT.jar

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: docker # 도커 작업이 완료 되면 실행
    permissions:
      id-token: write # OIDC 토큰을 사용하여 Infisical에 인증
      statuses: write # GitHub 상태 API에 대한 쓰기 권한

    steps:
      - name: Import Environment Variables from Infisical
        uses: Infisical/secrets-action@v1.0.7
        with:
          method: "oidc"
          env-slug: "prod"
          domain: "${{ secrets.INFISICAL_DOMAIN }}"
          project-slug: "github-actions"
          identity-id: "${{ secrets.INFISICAL_IDENTITY }}"
          secret-path: "/Handong-App-Deploy"

      - name: Send Deploy Request to DCA
        run: |
          curl --fail --request POST \
            --url "$DCA_ADDR" \
            --header "content-type: application/json" \
            --header "X-API-Key: $DCA_SECRET" \
            --data "{\"gh\": {\"commitSha\": \"$GITHUB_SHA\", \"githubRepo\": \"$GITHUB_REPOSITORY\", \"githubToken\": \"$GITHUB_TOKEN\"}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
